language: go
go:
  - 1.7
  - tip
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/modocache/gover
  - go get github.com/mikegleasonjr/forwardcache
script:
  - go vet github.com/mikegleasonjr/forwardcache
  - go test -v -race ./...
  - go list -f '{{if len .TestGoFiles}}"go test -coverprofile={{.Dir}}/.coverprofile {{.ImportPath}}"{{end}}' ./... | xargs -i sh -c {}
  - gover . coverage.txt
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt
